version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Future services for monorepo structure
  # api:
  #   build:
  #     context: ./packages/api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - NODE_ENV=production

  # workers:
  #   build:
  #     context: ./packages/workers
  #     dockerfile: Dockerfile
  #   environment:
  #     - NODE_ENV=production

networks:
  default:
    name: scriptyboy-network