version: '3.8'

services:
  app:
    image: ghcr.io/your-username/scripty:staging-latest
    environment:
      - NODE_ENV=staging
      - NEXT_PUBLIC_ENV=staging
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: on-failure

  # Load balancer for staging
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/staging.conf:/etc/nginx/nginx.conf
    depends_on:
      - app